apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbadger-price-bot
  labels:
    app: bbadger-price-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbadger-price-bot
  template:
    metadata:
      labels:
        app: bbadger-price-bot
    spec:
      serviceAccountName: bbadger-price-bot
      containers:
        - name: bbadger-price-bot
          image: IMAGE_NAME
          imagePullPolicy: IfNotPresent
          command: ["python", "scripts/run_bbadger_bot.py"]
          env:
            - name: LOG_LEVEL
              value: 'info'
            - name: BBADGER_ADDRESS
              value: '0x19D97D8fA813EE2f51aD4B4e04EA08bAf4DFfC28'
            - name: BOT_ID_BBADGER
              value: '835276359789576233'
