apiVersion: apps/v1
kind: Deployment
metadata:
  name: badger-price-bot
  labels:
    app: badger-price-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: badger-price-bot
  template:
    metadata:
      labels:
        app: badger-price-bot
    spec:
      containers:
        - name: badger-price-bot
          env:
            - name: LOG_LEVEL
              value: 'info'