name: Tag on Main - Build and Deploy to Production Environment
# Code should be validated in development environment before running this.
# Code is expected to work, but may have unexpected bugs.

on:
  push:
    tags:
      - 'v*'

env:
  TARGET_ENVIRONMENT: 'prd'
  MANIFEST_RESPOSITORY: 'badger-finance/powerflex_cloud_manifests'
  TAG_IMAGE_NAME: 'gcr.io/badger-finance/${{github.event.repository.name}}:${GITHUB_REF##*/}'

jobs:
  validate_manifest:
    name: Run Manifest Validation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Service
        uses: actions/checkout@main
      - name: Run Manifest Validation
        run: |
          make install_validate_manifest
          make validate_manifest TARGET_ENVIRONMENT=${{ env.TARGET_ENVIRONMENT }}

  deploy-prd:
    name: Release to Production Environemnt
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    needs: [validate_manifest]
    steps:
      - name: Checkout Service
        uses: actions/checkout@main
        with:
          fetch-depth: 2
      - id: vars
        name: Retreive Image ID
        run: |
          SHA=$(git rev-parse HEAD^2)
          echo "::set-output name=sha::$SHA"
      - name: Checkout Shared Actions
        uses: actions/checkout@main
        with:
          repository: badger-finance/ci_tools
          token: ${{ secrets.GH_TOKEN }}
          path: .github/badger-finance/ci_tools/
      - name: Setup Container Registry
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '297.0.0'
          service_account_key: ${{secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}
          export_default_credentials: true
      - name: Setup Docker Client
        uses: ./.github/badger-finance/ci_tools/registry-auth
      - name: Setup Build Container
        uses: ./.github/badger-finance/ci_tools/setup
        with:
          image: gcr.io/badger-finance/${{github.event.repository.name}}:${{ steps.vars.outputs.sha }}
      - name: Retag Container Image
        uses: ./.github/badger-finance/ci_tools/retag
        with:
          old_image_name: gcr.io/badger-finance/${{github.event.repository.name}}:${{ steps.vars.outputs.sha }}
          new_image_name: ${{ env.TAG_IMAGE_NAME }}
      - name: Deploy Tagged Container
        uses: ./.github/badger-finance/ci_tools/deploy
        with:
          image_tag: ${GITHUB_REF##*/}
          target_environment: prd
          manifest_repository: ${{ env.MANIFEST_RESPOSITORY }}
          gh_token: ${{ secrets.GH_TOKEN }}
      - name: Sign out
        uses: ./.github/badger-finance/ci_tools/signout

  notify:
    name: Notify Chat
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    needs: [deploy-prd]
    steps:
      - name: Notification to Slack
        uses: iRoachie/slack-github-actions@v2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notification to Teams
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: complete
          show-on-failure: true
